logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

api:
  external:
    subscriber-system:
      name: subscriber-system
      url: ${BALANCES_URL:localhost:8081/balance/}
      endpoint: all

full-path: ${api.external.subscriber-system.url}${api.external.subscriber-system.endpoint}

cache:
  fill-delay: 60
  refresh-delay: 60
  condition: 100.0

cloud:
    stream:
      bindings:
        notes-output:
          destination: app.api.balance
          binder: local_rabbit

server:
  port: 8082

spring:
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
